[project]
name = "the-power-of-queues"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery[redis]>=5.5.3",
    "pydantic-settings>=2.10.1",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
